import { useState } from 'react';
import Head from 'next/head';
import { Button, Form, Input, Modal, message } from 'antd';
import { signIn } from 'next-auth/react';
import { useRouter } from 'next/router';
export default function Home() {
	const [isModalVisible, setIsModalVisible] = useState(false);
	const [form] = Form.useForm();
	const router = useRouter();
	const onFinish = async values => {
		const { email, password } = values;
		const res = await signIn('credentials', {
			redirect: false,
			email,
			password,
			callbackUrl: `${window.location.origin}/dashboard`,
		});
		if (res?.error) {
			message.error(res.error);
		}
		if (res.url) {
			router.push(res.url);
		}
		form.resetFields();
	};
	const onFinishFailed = errorInfo => {
		console.log('Failed:', errorInfo);
	};
	const showModal = () => {
		setIsModalVisible(true);
	};
	const handleOk = () => {
		setIsModalVisible(false);
	};
	const handleCancel = () => {
		setIsModalVisible(false);
	};
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='container'>
				<Modal
					title='Basic Modal'
					visible={isModalVisible}
					footer={null}
					onOk={handleOk}
					onCancel={handleCancel}>
					<Form
						name='basic'
						form={form}
						labelCol={{
							span: 8,
						}}
						wrapperCol={{
							span: 16,
						}}
						initialValues={{
							remember: true,
						}}
						onFinish={onFinish}
						onFinishFailed={onFinishFailed}
						autoComplete='off'>
						<Form.Item
							label='Email Address'
							name='email'
							rules={[
								{
									required: true,
									type: 'email',
									message: 'The input is not valid E-mail!',
								},
							]}>
							<Input />
						</Form.Item>

						<Form.Item
							label='Password'
							name='password'
							rules={[
								{
									required: true,
									message: 'Please input your password!',
								},
							]}>
							<Input.Password />
						</Form.Item>

						<Form.Item
							wrapperCol={{
								offset: 8,
								span: 16,
							}}>
							<Button type='primary' htmlType='submit'>
								Submit
							</Button>
						</Form.Item>
					</Form>
				</Modal>
				<Button type='primary' onClick={showModal}>
					Open Modal
				</Button>
			</div>
		</>
	);
}
